=== siddharth2127/dbms/student.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="students">

        <xs:complexType>

            <xs:sequence>

                <xs:element name="student" maxOccurs="unbounded">

                    <xs:complexType>

                        <xs:sequence>

                            <xs:element name="rollNo" type="xs:integer"/>

                            <xs:element name="name" type="xs:string"/>

                            <xs:element name="department" type="xs:string"/>

                            <xs:element name="cgpa" type="xs:decimal"/>

                        </xs:sequence>

                    </xs:complexType>

                </xs:element>

            </xs:sequence>

        </xs:complexType>

    </xs:element>

</xs:schema>

=== siddharth2127/dbms/student.xml
<?xml version="1.0" encoding="UTF-8"?>

<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="student.xsd">

    <student>
        <rollNo>101</rollNo>
        <name>Arun</name>
        <department>CSE</department>
        <cgpa>8.5</cgpa>
    </student>

    <student>
        <rollNo>102</rollNo>
        <name>Divya</name>
        <department>IT</department>
        <cgpa>9.1</cgpa>
    </student>

</students>
